import { useState } from 'react';

export default function ReportModal({ item, listing, onClose }) {
  const [copied, setCopied] = useState(false);

  const reportText = `DMCA / Stolen Property Report

I am reporting a listing that I believe involves my stolen property.

Item: ${item?.name || '[Item Name]'}
Category: ${item?.category || '[Category]'}
Brand: ${item?.brand || '[Brand]'}
Serial Number: ${item?.serial_number || item?.serialNumber || 'N/A'}
Description: ${item?.description || '[Description]'}

Suspected Listing:
Title: ${listing?.title || '[Listing Title]'}
URL: ${listing?.listing_url || listing?.listingUrl || listing?.url || '[Listing URL]'}
Platform: ${listing?.platform || '[Platform]'}
Price: ${listing?.price || '[Price]'}
Location: ${listing?.location || '[Location]'}

I am the rightful owner of this property. This item was stolen/lost and I have reason to believe this listing is offering my property for sale. I request that this listing be removed and the seller's information be preserved for potential law enforcement inquiry.

I declare under penalty of perjury that the information in this notification is accurate and that I am the owner of the property that is allegedly being infringed.

Date: ${new Date().toLocaleDateString()}

---
Generated by RecoverWatch - Stolen Property Recovery Tool
`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const ta = document.createElement('textarea');
      ta.value = reportText;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[85vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <h2 className="text-lg font-semibold text-gray-900">
            Report to Platform
          </h2>
          <button
            onClick={onClose}
            className="p-1 text-gray-400 hover:text-gray-600 transition-colors"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="px-6 py-4 overflow-y-auto max-h-[55vh]">
          <p className="text-sm text-gray-600 mb-3">
            Copy the report template below and submit it to the platform. You can
            edit the text before submitting.
          </p>
          <pre className="bg-gray-50 rounded-lg p-4 text-sm text-gray-700 whitespace-pre-wrap font-mono border border-gray-200 leading-relaxed">
            {reportText}
          </pre>
        </div>

        {/* Footer */}
        <div className="flex flex-col sm:flex-row items-center gap-3 px-6 py-4 border-t border-gray-200 bg-gray-50">
          <button
            onClick={handleCopy}
            className="w-full sm:w-auto btn-amber flex items-center justify-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>
          <a
            href="https://www.ebay.com/help/policies/listing-policies/selling-stolen-property-policy?id=4279"
            target="_blank"
            rel="noopener noreferrer"
            className="w-full sm:w-auto text-center px-4 py-2 text-sm text-blue-600 hover:text-blue-700 font-medium border border-blue-200 rounded-lg hover:bg-blue-50 transition-colors"
          >
            eBay Reporting Page
          </a>
          <button
            onClick={onClose}
            className="w-full sm:w-auto px-4 py-2 text-sm text-gray-500 hover:text-gray-700 font-medium"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
